"""Initial migration

Revision ID: cf4a89cfb4c0
Revises: 
Create Date: 2026-04-12 16:10:36.279508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf4a89cfb4c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kg_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('kg_entity_types', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'PROCESSING', 'INDEXING', 'INDEXED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('chunk_count', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=True),
    sa.Column('page_count', sa.INTEGER(), nullable=False),
    sa.Column('image_count', sa.INTEGER(), nullable=False),
    sa.Column('table_count', sa.INTEGER(), nullable=False),
    sa.Column('parser_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('page_no', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=False),
    sa.Column('width', sa.INTEGER(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_table('document_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('page_no', sa.INTEGER(), nullable=False),
    sa.Column('content_markdown', sa.TEXT(), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=False),
    sa.Column('num_rows', sa.INTEGER(), nullable=False),
    sa.Column('num_cols', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('image_refs', sa.JSON(), nullable=True),
    sa.Column('thinking', sa.TEXT(), nullable=True),
    sa.Column('ratings', sa.JSON(), nullable=True),
    sa.Column('agent_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_workspace_id'), 'chat_messages', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_workspace_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('document_tables')
    op.drop_table('document_images')
    op.drop_table('documents')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
